[package]
name = "macros"
version = "0.1.0"
authors = ["inkyu <gofiri@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
common = {path = "../common"}

proc-macro2 = "0.4"
failure = "0.1"
quote = "0.6"